version: '3'
services:
  db:
    image: mysql:latest
    environment:
       MYSQL_DATABASE: lamp_docker
       MYSQL_USER: lamp_docker
       MYSQL_PASSWORD: cGFzc3dvcmQK
       MYSQL_ALLOW_EMPTY_PASSWORD: 1
       MYSQL_ROOT_PASSWORD: cGFzc3dvcmQK
  www:
    image: php:8.1-apache-buster
    volumes:
      - "./:/var/www/html"
    ports:
      - "80:80"
      - "443:443"
  phpmyapmin:
    image: phpmyadmin/phpmyadmin
    ports:
       - 8001:80
    environment:
      - PMA_HOST=db
      - PMA_PORT=3306